image:
  file: .gitpod.Dockerfile

tasks:
  - name: Playwright 102 Setup
    init: |
      # Install project dependencies
      npm install

      # Install Playwright browsers + Linux dependencies
      npx playwright install --with-deps
    command: |
      echo "✅ Gitpod workspace is ready."
      echo "Run tests with:"
      echo "  npx playwright test --project=chromium"
      echo "or headed:"
      echo "  npx playwright test --project=chromium --headed"

vscode:
  extensions:
    - ms-playwright.playwright
    - dbaeumer.vscode-eslint
